### ISSUE TITLE
Die GUI wird immer noch nicht richtig ausgeführt.

### ISSUE THREAD

**Issue by RedCyberSamurai** [MOTIVOKING/MOTIVO.KING#6]
GraphicalUserInterface::initialize() -> NullPointerException

**Comment by RedCyberSamurai** [comment]
GraphicalUserInterface::initialize() -> NullPointerException

**Comment by RedCyberSamurai** [comment]
tv_dates und column_date wurden noch nicht initialisiert

**Comment by butterklopsi** [comment]
die müssen nicht initialisiert werden ...

**Comment by RedCyberSamurai** [comment]
Wie erklärst du dann die Exception?
Ich seh da nur:
null::setCellValueFactory() und
null::setItems()...

**Comment by butterklopsi** [comment]
ja das ist weil diese `CellValueFactory` so nicht funktioniert ...

**Comment by RedCyberSamurai** [comment]
Warum hast du die dann so angelegt? Bzw, wozu ::initialize()?

**Comment by butterklopsi** [comment]
weil ich noch nciht dazu gekommen war, die zur funktion zu bringen, das initialize musste ich überschreiben, wegen irgednwas dassich implemntiert hatte ....

**Comment by RedCyberSamurai** [comment]
Ok.. Ich hoffe du hast die Änderung bei der GUI Klasse gesehen. Alles nach Application::launch() in derselbes Scope wird nicht ausgeführt.
Deswegen hab ich die Application Klasse verlagert und programLogic wird nun statisch nachgeladen.

**Comment by butterklopsi** [comment]
ich habe gesehen, dass du irgednwas geändert hast, aber da bei mir eh alles kapuut war zurpück gesetzt auf meinen letzten stand, aber ich kriege JavaFX mal wieder nicht etartet mometen ... :-/

**Comment by RedCyberSamurai** [comment]
Sag bescheid, falls ich helfen kann..

**Comment by butterklopsi** [comment]
ich glaube das erste problem habe ich ...

**Comment by butterklopsi** [comment]
ui startet erstmal wieder ...

**Comment by RedCyberSamurai** [comment]
Schön dass es bei dir funzt...

Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Location is not set.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at de.oszimt.fa45.motivoking.ui.GraphicalUserInterface.initRootLayout(GraphicalUserInterface.java:75)
	at de.oszimt.fa45.motivoking.ui.GraphicalUserInterface.start(GraphicalUserInterface.java:57)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	... 1 more

**Comment by butterklopsi** [comment]
versuch mal einmal in dem gradle fenster `clean `und dann `build `zu machen ....

**Comment by RedCyberSamurai** [comment]
Kann es sein, dass das Feature nur in der Ultimate verfügbar ist? Ich seh hier kein clean...

**Comment by RedCyberSamurai** [comment]
Hab jetzt einfach Invalidate Caches gemacht

**Comment by RedCyberSamurai** [comment]
Müsste deine .fxml nicht in /resources sein?

**Comment by butterklopsi** [comment]
nein das hat nichts mit intellij zu tun, das kannst du von der theorie auch aus der konsole machen, dass ist rein gradle#

**Comment by butterklopsi** [comment]
ist sie ja

**Comment by RedCyberSamurai** [comment]
ich seh die in /java/.../ui

**Comment by butterklopsi** [comment]
![image](https://cloud.githubusercontent.com/assets/10076918/20664169/5a6e3bf4-b55a-11e6-9e9d-1400e6a3961a.png)

**Comment by RedCyberSamurai** [comment]
Habs gemacht, die IDE gibt immer noch denselben Fehler an...

**Comment by butterklopsi** [comment]
das mit dem fxml war noch cnith richtig im git, sorry, habs gefixt zieh mal nochmal, vielleciht geht es dann wenn das fxml richtig liegt?

**Comment by RedCyberSamurai** [comment]
ok

**Comment by RedCyberSamurai** [comment]
Alles klar GUI "läuft"
Jetzt schau dir mal meine Änderung an, an sich hab ich nicht viel geändert, nur die Konsolenausgabe solltest du mal anschauen!!

**Comment by RedCyberSamurai** [comment]
private static GraphicalUserInterface instance;

public GraphicalUserInterface() {
        this.instance = this; // Das ist nonsense!! Statischer Context
                                        // GraphicalUserInterface.instance = this
}

**Comment by butterklopsi** [comment]
das sollte nichts ändern, denke ich ...

**Comment by RedCyberSamurai** [comment]
Wenn du mal in anderen Sprachen programmiert hättest... das wäre fatal

**Comment by RedCyberSamurai** [comment]
nur hast du die Konsole nun beachtet?

**Comment by butterklopsi** [comment]
ja wir programmieren gerade aber nicht in anderen sprachen .....

konsole beachtet? wie meinst du?

**Comment by RedCyberSamurai** [comment]
...
                Application.launch(GraphicalUserInterface.class);
                GraphicalUserInterface.getInstance().setProgramLogic(mProgramLogic);

                System.out.println(" -> GUI");
...

Ausführen:
> motivo/build/resources/main/de/oszimt/fa45/motivoking/ui/GraphicalUserInterface.fxml
> Graphical User Interface started

*stop*
> ######## NOPE ###########
> Process finished with exit code 0

**Comment by butterklopsi** [comment]
![image](https://cloud.githubusercontent.com/assets/10076918/20665275/4e8c9fc4-b55f-11e6-89a2-58400ed85ec2.png)
...

**Comment by RedCyberSamurai** [comment]
Jetzt schließe das Fenster

**Comment by butterklopsi** [comment]
ja, dann beendet sich das ganze programm

**Comment by RedCyberSamurai** [comment]
Hast du den master gepullt?

**Comment by butterklopsi** [comment]
kann jch nochmal machen

**Comment by butterklopsi** [comment]
ja jetzt, wo ist dein problem?

**Comment by RedCyberSamurai** [comment]
Hast du es nochmal laufen lassen?...

**Comment by RedCyberSamurai** [comment]
Ich sag ja nur:

> Application.launch(GraphicalUserInterface.class);
> GraphicalUserInterface.getInstance().setProgramLogic(mProgramLogic);

== 

> while(doAppStuff) {}
> GraphicalUserInterface.getInstance().setProgramLogic(mProgramLogic);

**Comment by butterklopsi** [comment]
???

**Comment by RedCyberSamurai** [comment]
> Application.launch(GraphicalUserInterface.class);
> // UNREACHABLE vvvvvvvvvvvvv
> GraphicalUserInterface.getInstance().setProgramLogic(mProgramLogic);

**Comment by butterklopsi** [comment]
häää??????
wo ist denn jetzt dein problem mit dem was funktioniert?

**Comment by RedCyberSamurai** [comment]
Hast du mal versucht in ::start() IRGENDETWAS von "programLogic" aufzurufen???

**Comment by butterklopsi** [comment]
nö 0:-)

**Comment by RedCyberSamurai** [comment]
Wie auch immer... ich wollte dir nur etwas Zeit ersparen... aber nein... mach dein Ding

**Comment by butterklopsi** [comment]
na ich verstehe nicht so richtig worauf du hinaus willst ....

**Comment by RedCyberSamurai** [comment]
Du wirst es sehen, wenn du deine Tabellen versuchst zu füllen. Nuff said.

**Comment by butterklopsi** [comment]
haben wir ein thread püroblem?

**Comment by RedCyberSamurai** [comment]
Könnte man meinen.
